/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef TestService_H
#define TestService_H

#include <TProcessor.h>
#include "test_types.h"



class TestServiceIf {
 public:
  virtual ~TestServiceIf() {}
  virtual void GetUserInfo(ResponseInfo& _return, const RequstInfo& req) = 0;
};

class TestServiceNull : virtual public TestServiceIf {
 public:
  virtual ~TestServiceNull() {}
  void GetUserInfo(ResponseInfo& /* _return */, const RequstInfo& /* req */) {
    return;
  }
};

typedef struct _TestService_GetUserInfo_args__isset {
  _TestService_GetUserInfo_args__isset() : req(false) {}
  bool req;
} _TestService_GetUserInfo_args__isset;

class TestService_GetUserInfo_args {
 public:

  TestService_GetUserInfo_args() {
  }

  virtual ~TestService_GetUserInfo_args() throw() {}

  RequstInfo req;

  _TestService_GetUserInfo_args__isset __isset;

  bool operator == (const TestService_GetUserInfo_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const TestService_GetUserInfo_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TestService_GetUserInfo_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class TestService_GetUserInfo_pargs {
 public:


  virtual ~TestService_GetUserInfo_pargs() throw() {}

  const RequstInfo* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TestService_GetUserInfo_result__isset {
  _TestService_GetUserInfo_result__isset() : success(false) {}
  bool success;
} _TestService_GetUserInfo_result__isset;

class TestService_GetUserInfo_result {
 public:

  TestService_GetUserInfo_result() {
  }

  virtual ~TestService_GetUserInfo_result() throw() {}

  ResponseInfo success;

  _TestService_GetUserInfo_result__isset __isset;

  bool operator == (const TestService_GetUserInfo_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const TestService_GetUserInfo_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TestService_GetUserInfo_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _TestService_GetUserInfo_presult__isset {
  _TestService_GetUserInfo_presult__isset() : success(false) {}
  bool success;
} _TestService_GetUserInfo_presult__isset;

class TestService_GetUserInfo_presult {
 public:


  virtual ~TestService_GetUserInfo_presult() throw() {}

  ResponseInfo* success;

  _TestService_GetUserInfo_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class TestServiceClient : virtual public TestServiceIf {
 public:
  TestServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  TestServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void GetUserInfo(ResponseInfo& _return, const RequstInfo& req);
  void send_GetUserInfo(const RequstInfo& req);
  void recv_GetUserInfo(ResponseInfo& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TestServiceProcessor : virtual public ::apache::thrift::TProcessor {
 protected:
  boost::shared_ptr<TestServiceIf> iface_;
  virtual bool process_fn(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, std::string& fname, int32_t seqid, void* callContext);
 private:
  std::map<std::string, void (TestServiceProcessor::*)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*)> processMap_;
  void process_GetUserInfo(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TestServiceProcessor(boost::shared_ptr<TestServiceIf> iface) :
    iface_(iface) {
    processMap_["GetUserInfo"] = &TestServiceProcessor::process_GetUserInfo;
  }

  virtual bool process(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot, void* callContext);
  virtual ~TestServiceProcessor() {}
};

class TestServiceMultiface : virtual public TestServiceIf {
 public:
  TestServiceMultiface(std::vector<boost::shared_ptr<TestServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TestServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<TestServiceIf> > ifaces_;
  TestServiceMultiface() {}
  void add(boost::shared_ptr<TestServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void GetUserInfo(ResponseInfo& _return, const RequstInfo& req) {
    uint32_t sz = ifaces_.size();
    for (uint32_t i = 0; i < sz; ++i) {
      if (i == sz - 1) {
        ifaces_[i]->GetUserInfo(_return, req);
        return;
      } else {
        ifaces_[i]->GetUserInfo(_return, req);
      }
    }
  }

};



#endif
